// Données mock
const vendors = [
    {
        id: 'v1',
        slug: 'ferme-des-batignolles',
        name: 'Ferme des Batignolles',
        shortDescription: 'Maraîcher bio livrant des paniers de saison sur Paris.',
        seoDescription: 'Producteur local bio proposant des paniers de légumes de saison en circuit court à Paris.',
        address: '12 rue des Moines',
        postalCode: '75017',
        city: 'Paris',
        labels: ['Bio', 'Circuit court'],
        imageUrl: 'https://ametzalde.fr/wp-content/uploads/2022/10/ferme-ametzalde-bio-pays-basque.jpg',
        products: []
    },
    {
        id: 'v2',
        slug: 'epicerie-vrac-11eme',
        name: 'Épicerie Vrac 11ème',
        shortDescription: 'Épicerie en vrac et zéro déchet dans le 11ème.',
        address: '45 rue Oberkampf',
        postalCode: '75011',
        city: 'Paris',
        labels: ['Zéro déchet', 'Vrac'],
        imageUrl: 'https://www.seinemaritime.fr/images/large/0809-sia-philippe-savale-la-ferme-du-vieux-puits03.webp',
        products: []
    }
]

const products = [
    {
        id: 'p1',
        slug: 'panier-legumes-bio-paris',
        name: 'Panier de légumes bio de saison',
        price: 24.9,
        vendorId: 'v1',
        category: 'Fruits et légumes',
        city: 'Paris',
        shortDescription: 'Un panier surprise de légumes bio de saison pour 2 à 3 personnes.',
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?w=800&h=600&fit=crop'
        ],
        longDescription: 'Notre panier de légumes bio est composé de produits frais récoltés le jour même dans nos fermes partenaires. Chaque semaine, découvrez une sélection variée de légumes de saison cultivés sans pesticides ni engrais chimiques. Idéal pour 2 à 3 personnes, ce panier vous garantit saveur et fraîcheur.',
        weight: '4-5 kg',
        origin: 'Île-de-France',
        composition: 'Tomates, carottes, courgettes, salades, pommes de terre, oignons (selon disponibilité saisonnière)',
        conservation: 'À conserver au frais, consommer dans les 7 jours',
        nutritionalInfo: 'Riche en vitamines, minéraux et fibres',
        certifications: ['Bio AB', 'Agriculture Biologique Européenne'],
        stock: 15
    },
    {
        id: 'p2',
        slug: 'cereales-vrac-bio',
        name: 'Céréales en vrac bio',
        price: 8.5,
        vendorId: 'v2',
        category: 'Épicerie',
        city: 'Paris',
        shortDescription: 'Avoine, riz complet, quinoa bio en vrac.',
        imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1536304929831-4f6d60c0e8e3?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&h=600&fit=crop'
        ],
        longDescription: 'Nos céréales bio sont sélectionnées avec soin auprès de producteurs certifiés. Vendues en vrac, elles vous permettent de réduire les emballages tout en profitant de produits de qualité supérieure. Parfaites pour un petit-déjeuner sain ou des préparations culinaires variées.',
        weight: 'Au choix (vendu au kg)',
        origin: 'France',
        composition: 'Mélange d\'avoine, riz complet et quinoa biologiques',
        conservation: 'À conserver dans un endroit sec, à l\'abri de la lumière',
        nutritionalInfo: 'Source de protéines végétales, fibres et magnésium',
        certifications: ['Bio AB'],
        stock: 50
    },
    {
        id: 'p4',
        slug: 'pain-complet-bio',
        name: 'Pain complet bio au levain',
        price: 4.2,
        vendorId: 'v2',
        category: 'Boulangerie',
        city: 'Paris',
        shortDescription: 'Pain au levain naturel, farine bio française.',
        imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=800&h=600&fit=crop'
        ],
        longDescription: 'Pain complet bio au levain naturel, pétri à la main et cuit au four traditionnel. Notre boulanger utilise uniquement de la farine bio française et un levain actif depuis plus de 20 ans. La fermentation lente permet d\'obtenir une mie aérée et une croûte croustillante.',
        weight: '500g',
        origin: 'France',
        composition: 'Farine complète bio T150, eau, levain naturel, sel',
        conservation: 'À conserver à température ambiante, consommer dans les 3-4 jours',
        nutritionalInfo: 'Riche en fibres et minéraux',
        certifications: ['Bio AB'],
        stock: 25
    },
    {
        id: 'p5',
        slug: 'fromage-chevre-fermier',
        name: 'Fromage de chèvre fermier',
        price: 6.8,
        vendorId: 'v1',
        category: 'Produits laitiers',
        city: 'Paris',
        shortDescription: 'Fromage de chèvre frais, production locale.',
        imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1628187838932-13f1c90a0faf?w=800&h=600&fit=crop'
        ],
        longDescription: 'Fromage de chèvre fermier à pâte fraîche, élaboré avec du lait cru de nos chèvres élevées en plein air. Texture onctueuse et saveur délicate, parfait pour les tartines ou en salade.',
        weight: '150g',
        origin: 'Île-de-France',
        composition: 'Lait cru de chèvre, ferments lactiques, sel',
        conservation: 'À conserver entre 2 et 6°C, consommer dans les 10 jours',
        nutritionalInfo: 'Source de calcium et protéines',
        certifications: ['Fermier'],
        stock: 18
    },
    {
        id: 'p6',
        slug: 'confitures-artisanales',
        name: 'Confitures artisanales',
        price: 7.5,
        vendorId: 'v2',
        category: 'Épicerie',
        city: 'Paris',
        shortDescription: 'Confitures maison, fruits de saison, recettes traditionnelles.',
        imageUrl: 'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1605896662828-38afbbaa1f6f?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1598965402089-897ce52e8330?w=800&h=600&fit=crop'
        ],
        longDescription: 'Confitures artisanales préparées en petite quantité avec des fruits de saison issus de l\'agriculture biologique. Cuisson traditionnelle au chaudron pour préserver le goût authentique des fruits. Plusieurs parfums disponibles.',
        weight: '250g',
        origin: 'France',
        composition: 'Fruits bio (60%), sucre de canne bio, jus de citron',
        conservation: 'À conserver au frais après ouverture',
        nutritionalInfo: '60% de fruits minimum',
        certifications: ['Bio AB', 'Fait maison'],
        stock: 30
    },
    {
        id: 'p8',
        slug: 'jus-pomme-artisanal',
        name: 'Jus de pomme artisanal',
        price: 4.9,
        vendorId: 'v2',
        category: 'Boissons',
        city: 'Paris',
        shortDescription: 'Jus de pomme 100% pur jus, sans additifs.',
        imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1584589167171-541ce45f1eea?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800&h=600&fit=crop'
        ],
        longDescription: 'Jus de pomme artisanal 100% pur jus, sans sucre ajouté ni conservateur. Pressé à froid pour conserver toutes les vitamines et saveurs naturelles des pommes bio.',
        weight: '1L',
        origin: 'France',
        composition: 'Jus de pomme bio 100%',
        conservation: 'À conserver au frais, consommer dans les 3 jours après ouverture',
        nutritionalInfo: 'Riche en vitamine C',
        certifications: ['Bio AB'],
        stock: 40
    },
    {
        id: 'p9',
        slug: 'herbes-aromatiques-pot',
        name: 'Herbes aromatiques en pot',
        price: 3.5,
        vendorId: 'v1',
        category: 'Jardin',
        city: 'Paris',
        shortDescription: 'Basilic, thym ou menthe, cultivés localement.',
        imageUrl: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1509587584298-0f3b3a3a1797?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=800&h=600&fit=crop'
        ],
        longDescription: 'Herbes aromatiques fraîches cultivées localement en pot. Apportez saveurs et fraîcheur à vos plats tout en décorant votre cuisine. Basilic, thym, menthe ou persil selon disponibilité.',
        weight: 'Pot 10cm',
        origin: 'Île-de-France',
        composition: 'Plant d\'herbe aromatique en pot biodégradable',
        conservation: 'Arroser régulièrement, placer près d\'une fenêtre',
        nutritionalInfo: 'Riche en antioxydants',
        certifications: ['Culture locale'],
        stock: 35
    },
    {
        id: 'p10',
        slug: 'tomates-cerises-bio',
        name: 'Tomates cerises bio',
        price: 5.9,
        vendorId: 'v1',
        category: 'Fruits et légumes',
        city: 'Paris',
        shortDescription: 'Tomates cerises bio gorgées de soleil, barquette de 500g.',
        imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1546470427-227c205c4fea?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1623681834365-58a2eaeb4f5c?w=800&h=600&fit=crop'
        ],
        longDescription: 'Tomates cerises bio cultivées en pleine terre, gorgées de soleil. Leur saveur sucrée et leur chair juteuse en font un incontournable des salades estivales et apéritifs.',
        weight: '500g',
        origin: 'Île-de-France',
        composition: 'Tomates cerises bio',
        conservation: 'À conserver à température ambiante, à l\'abri de la lumière',
        nutritionalInfo: 'Riche en vitamine C et lycopène',
        certifications: ['Bio AB'],
        stock: 22
    },
    {
        id: 'p11',
        slug: 'chocolat-artisanal-noir',
        name: 'Chocolat artisanal noir 70%',
        price: 6.5,
        vendorId: 'v2',
        category: 'Épicerie',
        city: 'Paris',
        shortDescription: 'Tablette de chocolat noir 70% cacao, fabrication artisanale.',
        imageUrl: 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1511381939415-e44015466834?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1606312619070-d48b4cda446f?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1548907086-4871c5c3a84e?w=800&h=600&fit=crop'
        ],
        longDescription: 'Chocolat noir 70% de cacao fabriqué artisanalement. Fèves de cacao équitables torréfiées et broyées à la pierre pour une texture fondante et des arômes intenses.',
        weight: '100g',
        origin: 'France (cacao Équateur)',
        composition: 'Pâte de cacao, sucre de canne, beurre de cacao',
        conservation: 'À conserver au sec, à l\'abri de la chaleur',
        nutritionalInfo: 'Source de magnésium et antioxydants',
        certifications: ['Bio AB', 'Commerce équitable'],
        stock: 45
    },
    {
        id: 'p12',
        slug: 'yaourt-fermier-nature',
        name: 'Yaourts fermiers nature',
        price: 4.8,
        vendorId: 'v1',
        category: 'Produits laitiers',
        city: 'Paris',
        shortDescription: 'Pot de 4 yaourts au lait entier, fabrication fermière.',
        imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1571212515674-44bd16c90cd1?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&h=600&fit=crop'
        ],
        longDescription: 'Yaourts fermiers nature au lait entier bio. Texture onctueuse et goût authentique grâce à une fabrication traditionnelle. Pack de 4 pots en verre consignés.',
        weight: '4 x 125g',
        origin: 'Île-de-France',
        composition: 'Lait entier bio, ferments lactiques',
        conservation: 'À conserver entre 2 et 6°C',
        nutritionalInfo: 'Riche en calcium et protéines',
        certifications: ['Bio AB', 'Fermier'],
        stock: 28
    },
    {
        id: 'p13',
        slug: 'salade-mesclun-bio',
        name: 'Mesclun bio frais',
        price: 3.2,
        vendorId: 'v1',
        category: 'Fruits et légumes',
        city: 'Paris',
        shortDescription: 'Mélange de jeunes pousses bio, sachet de 150g.',
        imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&h=600&fit=crop'
        ],
        longDescription: 'Mesclun bio composé d\'un mélange harmonieux de jeunes pousses tendres : roquette, mâche, laitue, épinards. Fraîchement cueilli pour une salade croquante et savoureuse.',
        weight: '150g',
        origin: 'Île-de-France',
        composition: 'Mélange de jeunes pousses bio (roquette, mâche, laitue, épinards)',
        conservation: 'À conserver au frais, consommer rapidement',
        nutritionalInfo: 'Riche en vitamines A, C et fer',
        certifications: ['Bio AB'],
        stock: 20
    },
    {
        id: 'p14',
        slug: 'huile-olive-extra-vierge',
        name: 'Huile d\'olive extra vierge',
        price: 15.9,
        vendorId: 'v2',
        category: 'Épicerie',
        city: 'Paris',
        shortDescription: 'Huile d\'olive première pression à froid, bouteille 500ml.',
        imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1608181919706-c1a5c1f65c3f?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=800&h=600&fit=crop'
        ],
        longDescription: 'Huile d\'olive extra vierge de première pression à froid. Olives récoltées à maturité optimale et pressées dans les 24h. Saveur fruitée et notes végétales délicates.',
        weight: '500ml',
        origin: 'Provence',
        composition: 'Huile d\'olive extra vierge 100%',
        conservation: 'À conserver à l\'abri de la lumière et de la chaleur',
        nutritionalInfo: 'Riche en acides gras mono-insaturés et vitamine E',
        certifications: ['Bio AB', 'AOP'],
        stock: 12
    },
    {
        id: 'p15',
        slug: 'pates-artisanales-bio',
        name: 'Pâtes artisanales bio',
        price: 5.5,
        vendorId: 'v2',
        category: 'Épicerie',
        city: 'Paris',
        shortDescription: 'Pâtes sèches bio au blé dur, séchage lent, 500g.',
        imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1551462147-37e8666446d7?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&h=600&fit=crop'
        ],
        longDescription: 'Pâtes artisanales bio fabriquées avec du blé dur français. Séchage lent à basse température pour préserver les qualités nutritionnelles. Texture rugueuse qui accroche parfaitement les sauces.',
        weight: '500g',
        origin: 'France',
        composition: 'Semoule de blé dur bio',
        conservation: 'À conserver au sec',
        nutritionalInfo: 'Source de glucides complexes et protéines',
        certifications: ['Bio AB', 'Artisanal'],
        stock: 38
    },
    {
        id: 'p16',
        slug: 'pommes-bio-varietes',
        name: 'Pommes bio variétés anciennes',
        price: 4.5,
        vendorId: 'v1',
        category: 'Fruits et légumes',
        city: 'Paris',
        shortDescription: 'Assortiment de pommes bio variétés anciennes, 1kg.',
        imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1619546952812-b58d34b178fa?w=800&h=600&fit=crop'
        ],
        longDescription: 'Assortiment de pommes bio de variétés anciennes cultivées dans nos vergers. Reinette, Boskoop, Belle de Boskoop selon saison. Saveurs authentiques et texture croquante.',
        weight: '1kg',
        origin: 'Île-de-France',
        composition: 'Pommes bio variétés anciennes',
        conservation: 'À conserver au frais ou à température ambiante',
        nutritionalInfo: 'Riche en fibres et antioxydants',
        certifications: ['Bio AB'],
        stock: 32
    },
    {
        id: 'p17',
        slug: 'beurre-fermier-demi-sel',
        name: 'Beurre fermier demi-sel',
        price: 3.8,
        vendorId: 'v1',
        category: 'Produits laitiers',
        city: 'Paris',
        shortDescription: 'Beurre artisanal au lait cru, demi-sel, 250g.',
        imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1628418397995-44b6c6552dcc?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1601612260736-5d35d0030ae7?w=800&h=600&fit=crop'
        ],
        longDescription: 'Beurre fermier demi-sel élaboré à partir de crème de lait cru. Barratage traditionnel et touche de sel de Guérande pour une saveur authentique et fondante.',
        weight: '250g',
        origin: 'Normandie',
        composition: 'Crème de lait cru, sel de Guérande (2%)',
        conservation: 'À conserver au réfrigérateur',
        nutritionalInfo: 'Riche en vitamine A et matières grasses laitières',
        certifications: ['Fermier', 'Lait cru'],
        stock: 24
    },
    {
        id: 'p18',
        slug: 'the-bio-infusions',
        name: 'Thé et infusions bio',
        price: 8.9,
        vendorId: 'v2',
        category: 'Boissons',
        city: 'Paris',
        shortDescription: 'Sélection de thés et infusions bio en vrac, 100g.',
        imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1597318130947-1a0ece18b2c1?w=800&h=600&fit=crop'
        ],
        longDescription: 'Sélection de thés et infusions bio en vrac. Thé vert, noir, blanc ou infusions de plantes selon vos préférences. Qualité premium pour un moment de détente.',
        weight: '100g',
        origin: 'Divers (thés certifiés bio)',
        composition: 'Thés et plantes aromatiques bio',
        conservation: 'À conserver au sec, à l\'abri de la lumière',
        nutritionalInfo: 'Riche en antioxydants',
        certifications: ['Bio AB'],
        stock: 50
    },
    {
        id: 'p19',
        slug: 'carottes-bio-botte',
        name: 'Carottes bio en botte',
        price: 2.9,
        vendorId: 'v1',
        category: 'Fruits et légumes',
        city: 'Paris',
        shortDescription: 'Botte de carottes fraîches bio avec fanes, environ 500g.',
        imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1447175008436-054170c2e979?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1522184216316-3c25379f9760?w=800&h=600&fit=crop'
        ],
        longDescription: 'Carottes bio fraîchement récoltées avec leurs fanes. Croquantes et sucrées, parfaites crues ou cuites. Les fanes peuvent être utilisées en soupe ou pesto.',
        weight: '500g',
        origin: 'Île-de-France',
        composition: 'Carottes bio avec fanes',
        conservation: 'À conserver au frais, consommer dans les 5 jours',
        nutritionalInfo: 'Riche en bêta-carotène et fibres',
        certifications: ['Bio AB'],
        stock: 27
    },
    {
        id: 'p21',
        slug: 'saucisson-sec-fermier',
        name: 'Saucisson sec fermier',
        price: 9.5,
        vendorId: 'v1',
        category: 'Charcuterie',
        city: 'Paris',
        shortDescription: 'Saucisson sec artisanal, séchage traditionnel, 250g.',
        imageUrl: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1623428184445-086c39e28d7e?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1612439530556-9f5ea042de7f?w=800&h=600&fit=crop'
        ],
        longDescription: 'Saucisson sec fermier élaboré avec de la viande de porc élevé en plein air. Séchage traditionnel de 6 semaines minimum pour des saveurs concentrées et authentiques.',
        weight: '250g',
        origin: 'France',
        composition: 'Viande de porc, sel, poivre, boyau naturel',
        conservation: 'À conserver au frais',
        nutritionalInfo: 'Source de protéines',
        certifications: ['Fermier', 'Label Rouge'],
        stock: 16
    },
    {
        id: 'p22',
        slug: 'coulis-tomate-bio',
        name: 'Coulis de tomate bio',
        price: 4.3,
        vendorId: 'v2',
        category: 'Épicerie',
        city: 'Paris',
        shortDescription: 'Coulis de tomate bio fait maison, bocal 500ml.',
        imageUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1546548970-71785318a17b?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1627997910241-966d551d32d0?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=800&h=600&fit=crop'
        ],
        longDescription: 'Coulis de tomate bio préparé avec des tomates mûries au soleil. Cuisson douce pour préserver les saveurs. Base idéale pour vos sauces, pizzas et plats mijotés.',
        weight: '500ml',
        origin: 'Provence',
        composition: 'Tomates bio, sel, basilic',
        conservation: 'À conserver au frais après ouverture',
        nutritionalInfo: 'Riche en lycopène',
        certifications: ['Bio AB'],
        stock: 34
    },
    {
        id: 'p23',
        slug: 'noix-melange-bio',
        name: 'Mélange de noix bio',
        price: 7.8,
        vendorId: 'v2',
        category: 'Épicerie',
        city: 'Paris',
        shortDescription: 'Mélange de noix, noisettes et amandes bio, sachet 300g.',
        imageUrl: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1508747703725-719777637510?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1585306427821-1f30e7af2c3e?w=800&h=600&fit=crop'
        ],
        longDescription: 'Mélange premium de noix, noisettes et amandes bio. Fruits secs entiers, non salés, parfaits pour un encas sain ou agrémenter vos salades et desserts.',
        weight: '300g',
        origin: 'France et Europe',
        composition: 'Noix, noisettes, amandes bio',
        conservation: 'À conserver au sec',
        nutritionalInfo: 'Riche en oméga-3, protéines et magnésium',
        certifications: ['Bio AB'],
        stock: 42
    },
    {
        id: 'p24',
        slug: 'citrouille-bio',
        name: 'Citrouille bio',
        price: 3.5,
        vendorId: 'v1',
        category: 'Fruits et légumes',
        city: 'Paris',
        shortDescription: 'Citrouille bio locale, environ 2kg.',
        imageUrl: 'https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=500&h=350&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1603893385035-e20c3c0c326c?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1508747703725-719777637510?w=800&h=600&fit=crop'
        ],
        longDescription: 'Citrouille bio cultivée localement. Chair tendre et sucrée, idéale pour les soupes, gratins et tartes. Également parfaite pour la décoration.',
        weight: 'Environ 2kg',
        origin: 'Île-de-France',
        composition: 'Citrouille bio',
        conservation: 'À conserver dans un endroit frais et sec',
        nutritionalInfo: 'Riche en vitamine A et fibres',
        certifications: ['Bio AB'],
        stock: 14
    }
]

export const getVendors = async () => vendors
export const getVendorBySlug = async (slug: string) =>
    vendors.find(v => v.slug === slug) ?? null

export const getProducts = async () => products
export const getProductBySlug = async (slug: string) =>
    products.find(p => p.slug === slug) ?? null

export const getProductsByArrondissement = async (arrondissement: string) =>
    products.filter(p => p.city === 'Paris') // Simule un filtre par arrondissement
